"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$package\
$nodejs\
$bun\
$deno\
$php\
$python\
$golang\
$java\
$gradle\
$lua\
$container\
$cmd_duration\
$status\
$line_break\
$os$character"""

[directory]
truncation_length = 3
truncate_to_repo = true
read_only = " 󰌾"

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold yellow"
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[status]
disabled = false
symbol = " "
format = "[$symbol$status]($style) "
style = "bold red"

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "bold yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold bright-blue"

[container]
symbol = "⬢ "
format = "[$symbol$name]($style) "

[gcloud]
disabled = true

[aws]
disabled = true

[kubernetes]
disabled = true

[docker_context]
disabled = true

[nodejs]
symbol = " "

[bun]
symbol = " "

[deno]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[gradle]
symbol = " "

[lua]
symbol = " "

[package]
symbol = "󰏗 "

[hostname]
ssh_symbol = " "

[os.symbols]
Arch = "󰣇"
CachyOS = "󰣇"
Debian = ""
Ubuntu = ""
Fedora = ""
Alpine = ""
NixOS = ""
Macos = ""
Windows = "󰍲"
Linux = ""
Unknown = ""