#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration

# Theme
foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #f5e0dc

# Cursor
cursor #f5e0dc
cursor_text_color #1e1e2e

# Colors
active_border_color #89b4fa
active_tab_background #89b4fa
color0 #45475a
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #f5c2e7
color6 #94e2d5
color7 #bac2de
color8 #585b70
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #a6adc8

# Font
font_family CaskaydiaCove Nerd Font Mono
font_size 10.0
bold_font auto
italic_font auto
bold_italic_font auto

# Window
window_padding_width 10
window_padding_height 10
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0
remember_window_size no
initial_window_width  950
initial_window_height 500

# Keybindings
#map alt+c copy_to_clipboard
#map alt+v paste_from_clipboard
map ctrl+left send_text normal \x1bb
map ctrl+right send_text normal \x1bf

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
enable_audio_bell no
background_opacity 0.9
dynamic_background_opacity 1

# Cursor
cursor_trail 1
cursor_shape block
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
selection_foreground        none
selection_background        none

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Animated cursor follows text
# include $HOME/.config/ml4w/settings/kitty-cursor-trail.conf

# Include wallpaper colors
# include colors-matugen.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
# include ./custom.conf

